### ISSUE TITLE
pretrained model testing.

### ISSUE THREAD

**Issue by pradheepram** [Cogito2012/UString#23]
so i did a test run of crash data set on the given pretrained models of RCNN and Usting vgg16 models. i got the same output as in the paper that is related to this project for the crash data set. I have the question that in the testing output of visualisations i find that all positive examples are almost always at a 1.0 or 0.0 probablity and all negative samples are in a similar state which shouldn't be the case as the probablity should be a fluctuating value. i don't think i have run the model wrongly since i got same results as in the paper.

video-level AP=0.99542
Average Precision= 0.9699, mean Time to accident= 4.7382
Recall@80%, Time to accident= 4.25
Mean aleatoric uncertainty: 0.013649
Mean epistemic uncertainty: 0.000099

The sample 20 test vis i got are:
![000152_pos](https://user-images.githubusercontent.com/80384494/171568614-ec62d5f3-f238-4d1f-b0da-ad96230764ed.png)
![000210_neg](https://user-images.githubusercontent.com/80384494/171568620-a32552bc-353a-4683-8bb1-065d345cdc2f.png)
![000218_neg](https://user-images.githubusercontent.com/80384494/171568624-aaea6fee-be1c-4f71-87c9-f3775e07a529.png)
![000311_pos](https://user-images.githubusercontent.com/80384494/171568625-4b77b141-287b-4969-a3f7-dd12810dccb4.png)
![000313_neg](https://user-images.githubusercontent.com/80384494/171568626-48da4982-35dc-4c8a-8ec9-d333c93876f7.png)
![000353_pos](https://user-images.githubusercontent.com/80384494/171568628-f1fb2c8e-40ce-4688-bb80-bb4b50e2ff0b.png)
![000430_neg](https://user-images.githubusercontent.com/80384494/171568633-d7a29714-b0e1-4e89-aaf4-6c6fd2435d36.png)
![000494_pos](https://user-images.githubusercontent.com/80384494/171568638-f7ffd04f-7f77-4b1e-af65-cf229dfa152e.png)
![000539_neg](https://user-images.githubusercontent.com/80384494/171568642-32652738-cdde-4c28-a2a4-9019dfb60fcb.png)
![000709_pos](https://user-images.githubusercontent.com/80384494/171568645-ee4a97a4-c0bd-4adc-bcf8-f9e48b983eb2.png)
![000796_pos](https://user-images.githubusercontent.com/80384494/171568649-608ce306-8b63-454a-81e2-7eac23b6b078.png)
![000849_pos](https://user-images.githubusercontent.com/80384494/171568653-4cc71475-9587-4f98-bd90-b2a0596802fb.png)
![000998_neg](https://user-images.githubusercontent.com/80384494/171568656-42635bd6-6d9b-4e42-9912-a547d162af41.png)
![001320_neg](https://user-images.githubusercontent.com/80384494/171568661-a05ec54f-a5ec-485d-b507-42b206056f4a.png)
![001451_neg](https://user-images.githubusercontent.com/80384494/171568665-0846f84c-9837-4821-8870-d9f610910fd1.png)
![001636_neg](https://user-images.githubusercontent.com/80384494/171568668-2a2445dc-5c7e-44b6-ae3a-f26851e31563.png)
![002254_neg](https://user-images.githubusercontent.com/80384494/171568676-4779ef13-fa1a-4b04-b837-5df9fd2d5ac0.png)
![002373_neg](https://user-images.githubusercontent.com/80384494/171568679-2dc3875b-2d65-44bc-84b7-be3213812f4f.png)
![002958_neg](https://user-images.githubusercontent.com/80384494/171568682-c027e979-047e-4848-a146-23f4fa35f4b6.png)
![002981_neg](https://user-images.githubusercontent.com/80384494/171568685-caacf864-37de-4ce4-aaf8-a9ba089e4988.png)

**Comment by LTNdeep** [comment]
Has the problem been resolved? My prediction also was wrong.

**Comment by Cogito2012** [comment]
@pradheepram @LTNdeep Thanks for your interest in this repo! 
The results should be correct. For the crash dataset, positive and negative videos are collected from different sources such that their visual quality/lighting/background, etc., are different, which leads the model to potentially overfitting to the scene (learn spurious correlation from accident-irrelevant cues). It would be promising to solve this issue from a technical perspective in the future :)

**Comment by LTNdeep** [comment]
I use the run_train_test.sh file to test and it only shows  20 results.Where can I set this parameter？

**Comment by Cogito2012** [comment]
> I use the run_train_test.sh file to test and it only shows 20 results.Where can I set this parameter？

What do you mean by 20 results? 
If you mean the number of output scores for each video, you may need to carefully double-check the `self.n_frames` and `self.fps` in your dataloader, see here for reference: [src/DataLoader.py#L22](https://github.com/Cogito2012/UString/blob/98b2d5a3f8cacedaa9a540806bd6da6a56bdaa77/src/DataLoader.py#L22).

**Comment by LTNdeep** [comment]
thanks.I have solved the problem.
