### ISSUE TITLE
How do I know the network architecture of the model?

### ISSUE THREAD

**Issue by Alex-fishred** [Cogito2012/UString#26]
How do I know the network architecture of the model?
I try to read the pth model with netron
I have tried torch.save to store the whole model instead of the model parameters only
but can't get the answer I want

I want to get the input and output dimensions of each layer, of course I can get it from the program code, but I don't believe my observation.

![未命名](https://github.com/Cogito2012/UString/assets/76515591/eaa26f07-96ba-4f06-af4e-58aeae38d310)

**Comment by Cogito2012** [comment]
You can debug the code line by line, and you can print all the input / output dimensions at each layer, as well as the complete network arch.
