### ISSUE TITLE
What classes are there in the object detection of KITTI training?

### ISSUE THREAD

**Issue by Alex-fishred** [Cogito2012/UString#27]
What are the cascade R_CNN categories trained by kitti?
What is the order?
If possible, I hope to know the classes set by mmdetection when it was originally trained

**Comment by Cogito2012** [comment]
@Alex-fishred The categories are the three commonly used Kitti classes: Car, Pedestrian, and Cyclist.
I cannot exactly remember the order but it should be likely in the order I listed.
