### ISSUE TITLE
CarCrashDataset - train/test split way

### ISSUE THREAD

**Issue by yiyiwwang** [Cogito2012/UString#31]
Thank you very much for your release of the [CarCrashDataset](https://github.com/Cogito2012/CarCrashDataset?tab=readme-ov-file#download).

Could you please give me your train.txt and test.txt? I haven’t found it in the download link.

Thank you very much!

**Comment by Cogito2012** [comment]
@yiyiwwang In the shared [google drive link](https://drive.google.com/drive/folders/1NUwC-bkka0-iPqhEhIgsXWtj0DA2MR-F?usp=sharing), they are under the folder `vgg16_features/`.
