### ISSUE TITLE
pre-trained Cascade R-CNN model files 

### ISSUE THREAD

**Issue by fdsaggaw** [Cogito2012/UString#7]
Hello, is there any problem with your pre-trained Cascade R-CNN model files ?When i run the demo.py,there are many errors in the bounding box.

**Comment by Cogito2012** [comment]
@fdsaggaw Thank you for your interest in this work! What do you mean by many errors in the bounding box? 

The Cascade R-CNN model was pre-trained on the KITTI 2D dataset and it should be fine. The bounding boxes used in this project are the selected top-K boxes with a low NMS threshold. Therefore, the visualized boxes may not with high quality as you expected.
